let yourAge = 26; 
//твой возраст;
let yearOfBirth = 1996;
//год рождения;
let numberOfBirth = 13 //(without a zero at the beginning);
//число рождения (без нолика в начале);
let numberOfSiblings = 1;
//количество родных братьев;
let numberOfSiblings = 2;
//количество родных сестер;
let numberOfPeopleInTheFamily = 6;
//количество человек в семье;
let theCostOfTravelToThePlaceOfStudy = 28;
//стоимость проезда до места обучения;
let currentYear = 2022;
//текущий год;
let dollarExchangeRate = 60.1;
//курс доллара;
let euroExchangeRate = 59.8;
//курс евро;
let bitcoinExchangeRate = 19875;
//курс биткоина;
