let gameName;
//название игры;
let descriptionOfTheGame;
//описание игры
let gameVersion;
//версия игры;
let nameOfTheMainCharacterOfTheGame;
//имя основного персонажа игры;
let nameOfTheGameDeveloper;
//имя разработчика игры;
let theProgrammingLanguageInWhichTheGameIsWritten;
//язык программирования, на которой написана игра;
let theVersionOfTheProgrammingLanguageInWhichTheGameIsWritten;
//версия языка программирования, на которой написана игра;
let theNameOfTheMapOnWhichTheGameTakesPlace;
//название карты, на которой происходят действия игры;
let gameDevelopersWebsite;
//сайт разработчика игры;
let interfaceLanguage;
//язык интерфейса;
